export const CREATED = 'created'
export const PENDING = 'pending'
export const RUNNING = 'running'
export const FAILED = 'failed'
export const SUCCESS = 'success'
export const CANCELED = 'canceled'
export const SKIPPED = 'skipped'
export const MANUAL = 'manual'
